### ISSUE TITLE
Force Rebuild of VCF Format Fields

### ISSUE THREAD

**Issue by ahadad** [CampagneLaboratory/goby#1]
When parsing new line in VCFParser class, force rebuild of format fields.

Error condition:

If previous line had GT,GG,GX; and new line has GT,GH,GX. The parser will return a value for GG, even though, GG is not defined for the current line.

**Comment by ahadad** [comment]
The given fix will not resolve the issue.

**Comment by fac2003** [comment]
Thanks for reporting the issue. Could you provide a small VCF file that demonstrates the problem? We would use this to make a JUnit test so we can verify the (i) problem exists in our latest code, (ii) verify a fix.

**Comment by fac2003** [comment]
I was not able to replicate this issue (see commit in stable branch for two junit tests that pass 991f3c1e352fe3a71d6f086efc494bc9a61bde1a). Could you send the piece of code and input file you used when you had this problem (as well as Goby version number)?

**Comment by ahadad** [comment]
The following is the content of a VCF that will exposed the issue. Notice that in the second line, I had changed the format field to contain GX instead of GQ. If you call on the parser to get the value for GQ when the parser is at that line, the parser will return the value that is for GX.

##fileformat=VCFv4.1
##INFO=<ID=AA,Number=1,Type=String,Description="Ancestral Allele, ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/pilot_data/technical/reference/ancestral_alignments/README">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total Depth">
##INFO=<ID=HM2,Number=0,Type=Flag,Description="HapMap2 membership">
##INFO=<ID=HM3,Number=0,Type=Flag,Description="HapMap3 membership">
##reference=human_b36_both.fasta
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
#CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  HG00096 HG00097 HG00099
1   695744  .   C   T   .   PASS    AA=.;DP=115 GT:GQ:DP    0|1:100:20  0|0:16:13   0|0:100:82
1   713682  rs11804171  T   A   .   PASS    AA=.;DP=137;HM2 GT:GX:DP    0|1:33:30   0|1:54:14   0|0:100:43
1   805474  .   C   T   .   PASS    AA=t;DP=210 GT:GQ:DP    0|0:3:35    0|0:4:33    0|0:100:88
1   837113  rs7416129   G   A   .   PASS    AA=a;DP=117 GT:GQ:DP    1|1:100:33  1|1:62:19   1|1:100:62
5   55855723    rs154255    C   T   .   PASS    AA=C;DP=132 GT:GQ:DP    1|0:100:36  0|0:77:26   1|0:100:70
5   55856063    rs6877810   C   G   .   PASS    AA=C;DP=124 GT:GQ:DP    0|1:100:28  0|0:68:22   0|0:100:65
5   56974534    rs2534843   T   C   .   PASS    AA=t;DP=99  GT:GQ:DP    1|1:10:15   0|1:57:19   1|0:100:61
5   56974644    .   G   T   .   PASS    AA=G;DP=85  GT:GQ:DP    1|0:75:17   1|0:60:17   1|1:49:46
10  134454818   rs2246580   G   A   .   PASS    AA=G;DP=98  GT:GQ:DP    1|1:71:30   1|1:4:5 1|1:100:53
10  134460004   rs60065392  A   G   .   PASS    AA=G;DP=116 GT:GQ:DP    0/1:100:28  0/1:100:18  0/1:100:73
20  1110696 rs6040355   A   G,T 67  PASS    NS=2;DP=10;AF=0.333,0.667;AA=T;DB   GT:GQ:DP:HQ 1|2:21:6:23,27  2|1:2:0:18,2    2/2:35:4
22  16050408    .   T   C   100 PASS    

LCSNP;EXSNP;BAVGPOST=0.982;BRSQ=0.850;LDAF=0.0616;AVGPOST=0.9811;RSQ=0.8689;ERATE=0.0020;THETA=0.0173;AC=130;AN=2184    GT:DS:GL:BD 0|0:0.033:-0.03,-1.17,-5.00:0.0014  

0|1:0.600:-0.71,-0.09,-5.00:0.9833  0|1:1.000:-4.10,-0.00,-3.28:1

My code general syntax is as follows:

vcfParser.readHeader();

do {

index = vcfParser.getGlobalFieldIndex(sampleName, formatField);
fieldValue = vcfParser.getFieldValue(index);

vcfParser.next();

} while (vcfParser.hasNextDataLine());

**Comment by ahadad** [comment]
Attached is the sample VCF.

Sincerely,

Ahmed Hadad
Sr. Analyst Programmer
Division of Research Education Systems Support
Phone: 507-538-1279
Email: hadad.ahmed@mayo.edumailto:hadad.ahmed@mayo.edu

**Comment by ahadad** [comment]
##fileformat=VCFv4.1
##INFO=<ID=AA,Number=1,Type=String,Description="Ancestral Allele, ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/pilot_data/technical/reference/ancestral_alignments/README">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total Depth">
##INFO=<ID=HM2,Number=0,Type=Flag,Description="HapMap2 membership">
##INFO=<ID=HM3,Number=0,Type=Flag,Description="HapMap3 membership">
##reference=human_b36_both.fasta
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
#CHROM             POS        ID            REF         ALT         QUAL    FILTER   INFO      FORMAT              HG00096
1              695744  .               C             T              .               PASS      AA=.;DP=115     GT:GQ:DP           0|1:100:20
1              713682  rs11804171          T              A             .               PASS      AA=.;DP=137;HM2          GT:GX:DP            0|1:33:30
1              805474  .               C             T              .               PASS      AA=t;DP=210     GT:GQ:DP           0|0:3:35
1              837113  rs7416129            G             A             .               PASS      AA=a;DP=117    GT:GQ:DP           1|1:100:33
5              55855723             rs154255              C             T              .               PASS      AA=C;DP=132    GT:GQ:DP           1|0:100:36
5              55856063             rs6877810            C             G             .               PASS      AA=C;DP=124    GT:GQ:DP           0|1:100:28
5              56974534             rs2534843            T              C             .               PASS      AA=t;DP=99       GT:GQ:DP           1|1:10:15
5              56974644             .               G             T              .               PASS      AA=G;DP=85      GT:GQ:DP           1|0:75:17
10           134454818           rs2246580            G             A             .               PASS      AA=G;DP=98      GT:GQ:DP           1|1:71:30
10           134460004           rs60065392          A             G             .               PASS      AA=G;DP=116   GT:GQ:DP           0/1:100:28
20           1110696                rs6040355            A             G,T         67           PASS      NS=2;DP=10;AF=0.333,0.667;AA=T;DB                GT:GQ:DP:HQ    1|2:21:6:23,27
22           16050408             .               T              C             100         PASS
LCSNP;EXSNP;BAVGPOST=0.982;BRSQ=0.850;LDAF=0.0616;AVGPOST=0.9811;RSQ=0.8689;ERATE=0.0020;THETA=0.0173;AC=130;AN=2184                GT:DS:GL:BD      0|0:0.033:-0.03,-1.17,-5.00:0.0014

Sincerely,

Ahmed Hadad
Sr. Analyst Programmer
Division of Research Education Systems Support
Phone: 507-538-1279
Email: hadad.ahmed@mayo.edumailto:hadad.ahmed@mayo.edu

**Comment by fac2003** [comment]
Please note that your example file is not valid VCF: the GX field is never declared. You need a ##FORMAT=<ID=GX line in the header to make this well-formed VCF. When I try the parser on this file, it fails as soon as I try to read the GX field, which is the correct behavior.  

However, after modifying the header I was able to reproduce the problem and fix it. See commit 998fed706cc4537efe77b417be347a6c2de92044

**Comment by fac2003** [comment]
The fix is now available in release 2.1.2.
