### ISSUE TITLE
dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/5/libgfortran.3.dylib

### ISSUE THREAD

**Issue by dancju** [CampagneLaboratory/goby#5]
I did these as instructed on README.

```
git clone git://github.com/CampagneLaboratory/goby.git
cd goby
git checkout stable
ant -f build.xml jar
```

So far no error reported.

```
$ ./goby
Trying to set RJAVA_HOME environment variable
dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/5/libgfortran.3.dylib
  Referenced from: /usr/local/Cellar/r/3.2.4_1/R.framework/Versions/3.2/Resources/lib/libR.dylib
  Reason: image not found

RJAVA_HOME=
java -ea -Xmx -Dlog4j.configuration=file:///Users/dan/Desktop/bio/goby/config/log4j-sample.properties -Djava.library.path= -jar /Users/dan/Desktop/bio/goby/goby.jar --mode
Invalid maximum heap size: -Xmx
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by fac2003** [comment]
You need to specify a memory option and mode name. Try:

At a minimum, you need to specify the memory setting to run goby, as in:

```
./goby 1g
```

This should print the help message describing what run modes are supported. After this works, you can specify a mode name after the memory setting, as in:

```
goby 1g version
```

Will print goby version number. If you need more details about options for a particular mode, do 

```
goby 1g MODE_NAME --help
```

Here's the output on my machine of running only "goby 1g" on my machine, using branch stable, before installing the rJava package:

Trying to set RJAVA_HOME environment variable

RJAVA_HOME=
java -ea -Xmx1g -Dlog4j.configuration=file:///Users/fac2003/IdeaProjects/git/goby/config/log4j-sample.properties -Djava.library.path= -jar /Users/fac2003/IdeaProjects/git/goby/goby.jar --mode
java -jar goby.jar (-m|--mode) <mode> [-h|--help] [-H|--x-help]

  (-m|--mode) <mode>
        Specifies which goby mode to run. Must be one of:
        \* aggregate-by-peak-distance (abpd)
        \* aggregate-by-peak-rpkm-difference (abprd)
        \* alignment-to-annotation-counts (atac)
        \* alignment-to-counts (altc)
        \* alignment-to-pileup (atp)
        \* alignment-to-read-set (atrs)
        \* alignment-to-text (att)
        \* alignment-to-transcript-counts (attc)
        \* annotation-penalty (ap)
        \* annotations-to-counts (antc)
        \* barcode-decoder (bd)
        \* base-stats (bs)
        \* bisulfite-conversion (bc)
        \* branch-point-detector (bpd)
        \* build-sequence-cache (bsc)
        \* compact-file-stats (cfs)
        \* compact-to-fasta (ctf)
        \* compact-to-sam (cts)
        \* concatenate-alignments (ca)
        \* concatenate-compact-reads (ccr)
        \* count-archive-to-peak-annotations (catpa)
        \* count-archive-to-peak-union-annotations (catpua)
        \* counts-to-bedgraph (ctb)
        \* counts-to-wiggle (ctw)
        \* coverage (c)
        \* diff-alignments (da)
        \* discover-sequence-variants
        \* display-sequence-variations
        \* empirical-p (ep)
        \* extract-splicing-events (ese)
        \* fasta-to-compact (ftc)
        \* fdr (f)
        \* files-to-attributes (fta)
        \* heptamer-weights (hw)
        \* infer-sex (is)
        \* last-to-compact (ltc)
        \* merge-compact-alignments (mca)
        \* methyl-stats (ms)
        \* read-quality-stats (rqs)
        \* reads-to-weights (rtw)
        \* reformat-compact-reads (rcr)
        \* run-parallel (rp)
        \* sam-comparison (sc)
        \* sam-extract-reads (ser)
        \* sam-to-compact (stc)
        \* sam-to-compact-old (stco)
        \* sam-to-compact-samhelper (stcs)
        \* sample-quality-scores (sqs)
        \* sequence-variation-stats (svs)
        \* sequence-variation-stats2 (svs2)
        \* set-to-text (stt)
        \* simulate-reads (sr)
        \* sort (s)
        \* sort-1 (s1)
        \* split-compact-reads (scr)
        \* split-fasta (sf)
        \* split-transcripts (st)
        \* stats
        \* suggest-position-slices (sps)
        \* tab-to-column-info (ttci)
        \* tally-bases (tb)
        \* tally-reads (tr)
        \* test-r-connection (trc)
        \* trim (t)
        \* upgrade (u)
        \* vcf-compare (vc)
        \* vcf-subset (vs)
        \* vcf-to-tab (vtt)
        \* version (v)
        \* within-group-variability (wgv)

  [-h|--help]
        Displays usage help information.

  [-H|--x-help]
        Displays help for dynamic options.

After installing rJava in R, running the same command yields:

Trying to set RJAVA_HOME environment variable
/Library/Frameworks/R.framework/Versions/3.2/Resources/library/rJava/jri
RJAVA_HOME=/Library/Frameworks/R.framework/Versions/3.2/Resources/library/rJava/jri
java -ea -Xmx1g -Dlog4j.configuration=file:///Users/fac2003/IdeaProjects/git/goby/config/log4j-sample.properties -Djava.library.path=/Library/Frameworks/R.framework/Versions/3.2/Resources/library/rJava/jri -jar /Users/fac2003/IdeaProjects/git/goby/goby.jar --mode
java -jar goby.jar (-m|--mode) <mode> [-h|--help] [-H|--x-help]

  (-m|--mode) <mode>
        Specifies which goby mode to run. Must be one of:
        \* aggregate-by-peak-distance (abpd)
        \* aggregate-by-peak-rpkm-difference (abprd)
        \* alignment-to-annotation-counts (atac)
        \* alignment-to-counts (altc)
        \* alignment-to-pileup (atp)
...

**Comment by fac2003** [comment]
Also note that if you do not care for calling R from Java, you can remove the bit that configures RJAVA_HOME from the goby wrapper script. This will get rid of the message you listed in the subject heading (it's machine dependent because it depends on which R packages you have installed on the machine where you run the script). 

The following is what you need to remove from the wrapper script:

```
if [ "${RJAVA_HOME:-notset}" == "notset" ]; then
  echo "Trying to set RJAVA_HOME environment variable"
  cat >/tmp/r-cmd.txt <<EOT
system.file("jri",package="rJava")
EOT
  tmpWithQuotes=`R --no-save </tmp/r-cmd.txt|grep [1]|tail -1 |awk '{print $2}'`
  temp="${tmpWithQuotes%\"}"
  temp="${temp#\"}"
  echo "$temp"
  export RJAVA_HOME=${temp}
  rm -f /tmp/r-cmd.txt
  echo "RJAVA_HOME=${RJAVA_HOME}"
fi
```

**Comment by dancju** [comment]
thank for that.
